server {
    listen 80;

    # 1. Отдача Фронтенда (React)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Для SPA (Single Page Application): если файл не найден, отдаем index.html
        try_files $uri $uri/ /index.html;
    }

    # 2. Проксирование API на Бэкенд
    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        client_max_body_size 20M; # Разрешаем загрузку файлов до 20МБ
    }

    # 3. Проксирование Админки и Swagger
    location /admin/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 4. Статика Админки (Django admin CSS/JS)
    # Эти файлы мы "прокинем" через volume из бэкенда
    location /static/ {
        alias /app/static/;
    }
}