# Generated by Django 6.0.2 on 2026-02-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100, unique=True, verbose_name='ID чата')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
