# Generated by Django 6.0.2 on 2026-02-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Входящее'), ('outbound', 'Исходящее')], max_length=10)),
                ('sender', models.CharField(max_length=255)),
                ('recipient', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('body_text', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500, verbose_name='Тема')),
                ('sender_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('object_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Объект/Предприятие')),
                ('serial_numbers', models.TextField(blank=True, null=True, verbose_name='Заводские номера')),
                ('device_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип прибора')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Суть вопроса (AI)')),
                ('category', models.CharField(choices=[('malfunction', 'Неисправность'), ('calibration', 'Калибровка'), ('docs', 'Запрос документации'), ('software', 'Подключение и ПО'), ('password', 'Запрос пароля'), ('mounting', 'Монтаж и установка'), ('warranty', 'Гарантия и ремонт'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Категория')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('ai_processed', 'Обработан AI'), ('in_progress', 'В работе'), ('awaiting_reply', 'Ожидает ответа'), ('resolved', 'Решён'), ('closed', 'Закрыт')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='medium', max_length=20)),
                ('sentiment', models.CharField(choices=[('positive', 'Позитивный'), ('neutral', 'Нейтральный'), ('negative', 'Негативный')], default='neutral', max_length=20)),
                ('confidence', models.FloatField(default=0.0, null=True)),
                ('ai_draft', models.TextField(blank=True, null=True, verbose_name='Черновик AI')),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_body', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
