# Generated by Django 6.0.2 on 2026-02-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Неисправность', 'Неисправность'), ('Калибровка', 'Калибровка'), ('Запрос документации', 'Запрос документации'), ('Подключение и ПО', 'Подключение и ПО'), ('Запрос пароля', 'Запрос пароля'), ('Монтаж и установка', 'Монтаж и установка'), ('Гарантия и ремонт', 'Гарантия и ремонт'), ('Другое', 'Другое')], default='Другое', max_length=100, verbose_name='Категория'),
        ),
    ]
