# Generated by Django 6.0.2 on 2026-02-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ai_draft_reply',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='confidence_score',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ai_draft',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='confidence',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sender_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('ai_processed', 'Обработан AI'), ('in_progress', 'В работе'), ('awaiting_reply', 'Ожидает ответа'), ('resolved', 'Решён'), ('closed', 'Закрыт')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
