# Generated by Django 6.0.2 on 2026-02-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='description',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ai_draft',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Неисправность', 'Неисправность'), ('Калибровка', 'Калибровка'), ('Запрос документации', 'Запрос документации'), ('Подключение и ПО', 'Подключение и ПО'), ('Запрос пароля', 'Запрос пароля'), ('Монтаж и установка', 'Монтаж и установка'), ('Гарантия и ремонт', 'Гарантия и ремонт'), ('Другое', 'Другое')], default='Другое', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='object_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Объект'),
        ),
    ]
