# Generated by Django 6.0.2 on 2026-02-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_remove_ticket_assigned_to_remove_ticket_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('awaiting_reply', 'Ожидает ответа'), ('resolved', 'Решён'), ('closed', 'Закрыт')], default='new', max_length=20),
        ),
    ]
